/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import Classe.LivroData;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import model.LivroSALVA;
/**
 *
 * @author Aluno
 */

public class FrmLivros1 extends javax.swing.JFrame {
private LivroSALVA Coleta;
private LivroData DAO;
    /**
     * Creates new form FrmLivros1
     */
    public FrmLivros1() {
        initComponents();
        DAO = new LivroData();
        
        URL caminhoIcone= getClass().getResource("/img/soraiva2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtautor = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtidade = new javax.swing.JTextField();
        txtcpf = new javax.swing.JTextField();
        txtrg = new javax.swing.JTextField();
        txtano = new javax.swing.JTextField();
        txteditora = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtnomelivro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnpesquisar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cbogenero = new javax.swing.JComboBox<>();

        jLabel13.setText("jLabel13");

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sóraiva");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/saraivaplb.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 200, 60));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Idade:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("RG:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("Ano de lançamento:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Genero do Livro:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setText("Editora:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setText("ID Livro:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setText("Nome Livro:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel11.setText("Autor:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));
        getContentPane().add(txtautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 150, -1));
        getContentPane().add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 150, -1));
        getContentPane().add(txtidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 150, -1));
        getContentPane().add(txtcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 150, -1));
        getContentPane().add(txtrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 150, -1));
        getContentPane().add(txtano, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 150, -1));
        getContentPane().add(txteditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 150, -1));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 150, -1));
        getContentPane().add(txtnomelivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 150, -1));

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 100, 70));

        jButton2.setText("Deletar registro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 130, 70));

        btnpesquisar.setText("Pesquisar");
        btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnpesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 120, -1));

        jButton4.setText("Sair");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 110, 70));

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 100, 70));

        jButton5.setText("About");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 120, -1));

        jButton6.setText("Atualizar registro");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 130, 70));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/10-livros-que-podem-te-ajudar-a-ficar-rico-em-2016-notic.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 640, 290));

        cbogenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto-Ajuda ", "Ciência ", "Culinária | Gastronomia ", "Esoterismo ", "Fantasia | Ficção ", "Filosofia ", "Guerra ", "História ", "Lingüistica ", "Lit. Estrangeira", "Lit. Infanto-Juvenil ", "Lit. Nacional ", "Medicina ", "Música ", "Política ", "Psicologia ", "Romance ", "Quadrinhos ", "Religião ", "Saúde ", "Sexo ", "Terror ", "Vestibular ", "Cronica ", "Poesia ", "Poemas ", "Conto" }));
        getContentPane().add(cbogenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        String g;
        g=JOptionPane.showInputDialog("Deseja realmente sair ? S ou N");

        if("S".equals(g) || "s".equals(g))
        System.exit(0);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        FrmSobre u = new FrmSobre();
        u.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
        if(validarCampos()){
    if(preencher()){
        if(DAO.Incluir(Coleta)){
        JOptionPane.showMessageDialog(this, "Cadastrado com sucesso");
       
    }
}       
}else{
    JOptionPane.showMessageDialog(this, "Não foi possivel concluir");
}
}catch (Exception erro){
    JOptionPane.showMessageDialog(this, "Erro:"+erro.getMessage());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisarActionPerformed
        try{
        if(txtid.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo ID_Livro");
            txtid.requestFocus();
        }
            LivroSALVA Coleta = DAO.pesquisar(Integer.parseInt(txtid.getText()));
        
        if(Coleta==null){
            JOptionPane.showMessageDialog(this, "Não existem registros com esse ID");
            txtid.setText("");
       }
        else{
            txtnome.setText(Coleta.getNome());
            txtidade.setText(Integer.toString(Coleta.getIdade()));
            txtcpf.setText(Integer.toString(Coleta.getCPF()));
            txtrg.setText(Integer.toString(Coleta.getRG()));
            txtano.setText(Integer.toString(Coleta.getAno_Lançamento()));
            cbogenero.setSelectedItem(Coleta.getGenero_Livro());
            txteditora.setText(Coleta.getEditora());
            
            txtnomelivro.setText(Coleta.getNome_Livro());
            txtautor.setText(Coleta.getAutor());
        }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this, "Erro"+erro.getMessage());
        }
    }//GEN-LAST:event_btnpesquisarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtnome.setText(null);
            txtidade.setText(null);
            txtcpf.setText(null);
            txtrg.setText(null);
            txtano.setText(null);
            cbogenero.setSelectedItem(null);
            txteditora.setText(null);
            txtid.setText(null);
            txtnomelivro.setText(null);
            txtautor.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
        if(validarCampos()){
    if(preencher()){
        if(DAO.Editar(Coleta)){
        JOptionPane.showMessageDialog(this, "Registro atualizado com sucesso");
       
    }
}       
}else{
    JOptionPane.showMessageDialog(this, "Não foi atualizar");
}
}catch (Exception erro){
    JOptionPane.showMessageDialog(this, "Erro:"+erro.getMessage());
}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
        if(txtid.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Preencha o campo ID Livro");
            
        }else
            {
                if(DAO.Excluir(Integer.parseInt(txtid.getText()))){
        JOptionPane.showMessageDialog(this, "Registro deletado com sucesso"); 
            }
                else{
                    JOptionPane.showMessageDialog(this, "Não foi possivel deletar");
                }
            }
            }catch(Exception erro){
                    JOptionPane.showMessageDialog(this, "Erro"+erro.getMessage());
                    }
        txtnome.setText(null);
            txtidade.setText(null);
            txtcpf.setText(null);
            txtrg.setText(null);
            txtano.setText(null);
            cbogenero.setSelectedItem(null);
            txteditora.setText(null);
            txtid.setText(null);
            txtnomelivro.setText(null);
            txtautor.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLivros1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLivros1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLivros1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLivros1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLivros1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpesquisar;
    private javax.swing.JComboBox<String> cbogenero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtano;
    private javax.swing.JTextField txtautor;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txteditora;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidade;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnomelivro;
    private javax.swing.JTextField txtrg;
    // End of variables declaration//GEN-END:variables
public boolean validarCampos(){
    if(txtnome.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Preencha o campo Nome");
      txtnome.requestFocus();
      return false;
    }
    if(txtidade.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Preencha o campo Idade");
      txtidade.requestFocus();
      return false;
    }
     if(txtcpf.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Preencha o campo CPF");
      txtcpf.requestFocus();
      return false;
    }
      if(txtrg.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Preencha o campo RG");
      txtrg.requestFocus();
      return false;
    }
       if(txtano.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Preencha o campo Ano");
      txtano.requestFocus();
      return false;
    }
        if(cbogenero.getSelectedItem().equals("")){
      JOptionPane.showMessageDialog(this, "Preencha o campo Genero do livro");
      cbogenero.requestFocus();
      return false;
    }
         if(txteditora.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Preencha o campo Editora");
      txteditora.requestFocus();
      return false;
    }
          if(txtid.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Preencha o campo ID livro");
      txtid.requestFocus();
      return false;
    }
           if(txtnomelivro.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Preencha o campo Nome livro");
      txtnomelivro.requestFocus();
      return false;
    }
            if(txtautor.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Preencha o campo Autor");
      txtautor.requestFocus();
      return false;
    }
           
    return true;
}
public boolean preencher(){
    Coleta = new LivroSALVA();
    Coleta.setNome(txtnome.getText());
    Coleta.setIdade(Integer.parseInt(txtidade.getText()));
    Coleta.setCPF(Integer.parseInt(txtcpf.getText()));
    Coleta.setRG(Integer.parseInt(txtrg.getText()));  
    Coleta.setAno_Lançamento(Integer.parseInt(txtano.getText()));
    Coleta.setGenero_Livro(Integer.toString(cbogenero.getSelectedIndex()));
    Coleta.setEditora(txteditora.getText());
    Coleta.setID_Livro(Integer.parseInt(txtid.getText()));
    Coleta.setNome_Livro(txtnomelivro.getText());
    Coleta.setAutor(txtautor.getText());
    
    return true;
}

}
